name: Release Firmware

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          target: esp32c3

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/irrigation.bin
