name: Release Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          version: "latest"

      - name: Build firmware
        run: |
          idf.py set-target esp32c3
          idf.py build

      - name: Upload firmware to release
        uses: softprops/action-gh-release@v1
        with:
          files: build/irrigation.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
